;
; ACIA TOGGLE RTS
;
        ORG  $FFD0
;
; INITIALIZE THE ACIA
; 
START   LDAA #$03
        STAA $E000      ;MASTER RESET THE ACIA
        NOP
        NOP
; INITIALIZE THE ACIA FOR:
; RX INTERRUPT DISABLED
; RTS LOW TRANSMIT INTERRUPT DISABLED
; 8 BITS, ONE STOP BIT, /16 BAUD CLOCK
;
        CLRB
LOOP    LDAA #$15
        STAA $E000      ;MAKE RTS LOW
DELAY   DECB
        BNE  DELAY
        LDAA #$55
        STAA $E000      ;MAKE RTS HIGH
DELAY1  DECB
        BNE  DELAY1
        BRA  LOOP
;
;VECTORS
;
        ORG  $FFF8

IRQA    FDB  START
SWI     FDB  START
NMI     FDB  START
RESET   FDB  START
        END
